#include "TestFramework.h"

#include <Fluxion/RHI/Capabilities.h>

void Test_Capabilities_Run(TestContext* ctx)
{
    FluxionRHICapabilityFlags caps = FLUXION_RHI_CAPABILITY_NONE;
    TEST_CHECK(ctx, (caps & FLUXION_RHI_CAPABILITY_BINDLESS_RESOURCES) == 0);

    caps |= FLUXION_RHI_CAPABILITY_BINDLESS_RESOURCES;
    caps |= FLUXION_RHI_CAPABILITY_RAY_TRACING;

    TEST_CHECK(ctx, (caps & FLUXION_RHI_CAPABILITY_BINDLESS_RESOURCES) != 0);
    TEST_CHECK(ctx, (caps & FLUXION_RHI_CAPABILITY_RAY_TRACING) != 0);
    TEST_CHECK(ctx, (caps & FLUXION_RHI_CAPABILITY_MESH_SHADERS) == 0);

    // Every flag must be distinct (a copy-paste bit-shift typo would
    // silently alias two capabilities onto the same bit).
    FluxionRHICapabilityFlags all =
        FLUXION_RHI_CAPABILITY_BINDLESS_RESOURCES | FLUXION_RHI_CAPABILITY_DESCRIPTOR_INDEXING |
        FLUXION_RHI_CAPABILITY_MESH_SHADERS | FLUXION_RHI_CAPABILITY_RAY_TRACING | FLUXION_RHI_CAPABILITY_RAY_QUERY |
        FLUXION_RHI_CAPABILITY_VARIABLE_RATE_SHADING | FLUXION_RHI_CAPABILITY_ASYNC_COMPUTE | FLUXION_RHI_CAPABILITY_ASYNC_TRANSFER |
        FLUXION_RHI_CAPABILITY_BUFFER_DEVICE_ADDRESS | FLUXION_RHI_CAPABILITY_INDIRECT_COUNT | FLUXION_RHI_CAPABILITY_TIMELINE_SYNC |
        FLUXION_RHI_CAPABILITY_COMPUTE_SHADERS | FLUXION_RHI_CAPABILITY_TESSELLATION | FLUXION_RHI_CAPABILITY_GEOMETRY_SHADERS |
        FLUXION_RHI_CAPABILITY_FP16 | FLUXION_RHI_CAPABILITY_INT64 | FLUXION_RHI_CAPABILITY_WAVE_OPERATIONS | FLUXION_RHI_CAPABILITY_SPARSE_RESOURCES;

    int bitCount = 0;
    for (int bit = 0; bit < 64; ++bit)
    {
        if (all & ((FluxionRHICapabilityFlags)1 << bit)) ++bitCount;
    }
    TEST_CHECK(ctx, bitCount == 18);
}
