#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// Portable key identifiers — every backend (Win32 VK_*, X11 KeySym)
// translates into this set. FLUXION_KEY_COUNT sizes the fixed keyboard
// state arrays in Input.c; add new keys before it, never after.
typedef enum FluxionKeyCode
{
    FLUXION_KEY_UNKNOWN = 0,

    FLUXION_KEY_A, FLUXION_KEY_B, FLUXION_KEY_C, FLUXION_KEY_D, FLUXION_KEY_E,
    FLUXION_KEY_F, FLUXION_KEY_G, FLUXION_KEY_H, FLUXION_KEY_I, FLUXION_KEY_J,
    FLUXION_KEY_K, FLUXION_KEY_L, FLUXION_KEY_M, FLUXION_KEY_N, FLUXION_KEY_O,
    FLUXION_KEY_P, FLUXION_KEY_Q, FLUXION_KEY_R, FLUXION_KEY_S, FLUXION_KEY_T,
    FLUXION_KEY_U, FLUXION_KEY_V, FLUXION_KEY_W, FLUXION_KEY_X, FLUXION_KEY_Y,
    FLUXION_KEY_Z,

    FLUXION_KEY_0, FLUXION_KEY_1, FLUXION_KEY_2, FLUXION_KEY_3, FLUXION_KEY_4,
    FLUXION_KEY_5, FLUXION_KEY_6, FLUXION_KEY_7, FLUXION_KEY_8, FLUXION_KEY_9,

    FLUXION_KEY_F1, FLUXION_KEY_F2, FLUXION_KEY_F3, FLUXION_KEY_F4,
    FLUXION_KEY_F5, FLUXION_KEY_F6, FLUXION_KEY_F7, FLUXION_KEY_F8,
    FLUXION_KEY_F9, FLUXION_KEY_F10, FLUXION_KEY_F11, FLUXION_KEY_F12,

    FLUXION_KEY_ESCAPE,
    FLUXION_KEY_TAB,
    FLUXION_KEY_CAPS_LOCK,
    FLUXION_KEY_LEFT_SHIFT,
    FLUXION_KEY_RIGHT_SHIFT,
    FLUXION_KEY_LEFT_CONTROL,
    FLUXION_KEY_RIGHT_CONTROL,
    FLUXION_KEY_LEFT_ALT,
    FLUXION_KEY_RIGHT_ALT,
    FLUXION_KEY_SPACE,
    FLUXION_KEY_ENTER,
    FLUXION_KEY_BACKSPACE,
    FLUXION_KEY_DELETE,
    FLUXION_KEY_INSERT,
    FLUXION_KEY_HOME,
    FLUXION_KEY_END,
    FLUXION_KEY_PAGE_UP,
    FLUXION_KEY_PAGE_DOWN,

    FLUXION_KEY_UP,
    FLUXION_KEY_DOWN,
    FLUXION_KEY_LEFT,
    FLUXION_KEY_RIGHT,

    FLUXION_KEY_NUMPAD_0, FLUXION_KEY_NUMPAD_1, FLUXION_KEY_NUMPAD_2,
    FLUXION_KEY_NUMPAD_3, FLUXION_KEY_NUMPAD_4, FLUXION_KEY_NUMPAD_5,
    FLUXION_KEY_NUMPAD_6, FLUXION_KEY_NUMPAD_7, FLUXION_KEY_NUMPAD_8,
    FLUXION_KEY_NUMPAD_9,

    FLUXION_KEY_COUNT,
} FluxionKeyCode;

#ifdef __cplusplus
}
#endif
