# The contents of this file are subject to the Common Public Attribution
# License Version 1.0 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# https://opensource.org/license/cpal-1-0. The License is based on the
# Mozilla Public License Version 1.1 but Sections 14 and 15 have been added
# to cover use of software over a computer network and provide for limited
# attribution for the Original Developer. In addition, Exhibit A has been
# modified to be consistent with Exhibit B.
#
# Software distributed under the License is distributed on an "AS IS" basis,
# WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
# for the specific language governing rights and limitations under the
# License.
#
# The Original Code is Fluxion Engine.
#
# The Original Developer is not the Initial Developer and is __________. If
# left blank, the Original Developer is the Initial Developer.
#
# The Initial Developer of the Original Code is Kiss Tibor Péter. All
# portions of the code written by Kiss Tibor Péter are Copyright (c) 2026.
# All Rights Reserved.
#
# Contributor ______________________.
#
# Alternatively, the contents of this file may be used under the terms of
# the Fluxion Engine Commercial License Agreement Version 1.0, separately
# obtained from and valid as granted by Kiss Tibor Péter (the "Commercial
# License"), in which case the provisions of the Commercial License are
# applicable instead of those above.
#
# If you wish to allow use of your version of this file only under the terms
# of the Commercial License and not to allow others to use your version of
# this file under the CPAL, indicate your decision by deleting the
# provisions above and replace them with the notice and other provisions
# required by the Commercial License. If you do not delete the provisions
# above, a recipient may use your version of this file under either the CPAL
# or the Commercial License.
#
# SPDX-License-Identifier: CPAL-1.0

include_guard(GLOBAL)

# engine_embed_shader_library(
#     OUTPUT <generated-source-var>   # receives the path to write into a target's SOURCES
#     ROOT   <dir>                    # the directory the include names are relative to
#     FILES  <file>...                # shader library sources, relative to ROOT
# )
#
# Turns the engine's own shader library into a C++ source that carries the
# text of each file, so a built program contains its shader library rather
# than looking for it.
#
# It is built in rather than loaded because the library is engine code in
# every way that matters: a library and an engine that disagree produce
# shaders that COMPILE AND LIGHT WRONGLY, which is the worst way for two
# things to be out of step. Making them inseparable removes the question.
#
# The files stay real .jsl files on disk -- an editor can highlight them,
# a diff can read them, and nothing is written twice.
function(engine_embed_shader_library)
    set(oneValueArgs OUTPUT ROOT)
    set(multiValueArgs FILES)
    cmake_parse_arguments(ENGINE_SHADER_LIB "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

    if(NOT ENGINE_SHADER_LIB_OUTPUT OR NOT ENGINE_SHADER_LIB_ROOT OR NOT ENGINE_SHADER_LIB_FILES)
        message(FATAL_ERROR "engine_embed_shader_library: OUTPUT, ROOT and FILES are all required")
    endif()

    set(ENGINE_SHADER_LIB_GENERATED "${CMAKE_CURRENT_BINARY_DIR}/FluxionShaderLibrary_Generated.cpp")

    set(ENGINE_SHADER_LIB_BODY "")
    string(APPEND ENGINE_SHADER_LIB_BODY
        "// Generated by engine_embed_shader_library(). Do not edit.\n"
        "//\n"
        "// The engine's own shader library, as text. The sources are under\n"
        "// Source/RenderCore/Shaders/ -- edit those.\n"
        "\n"
        "namespace Fluxion::RenderCore\n"
        "{\n"
        "namespace\n"
        "{\n"
        "struct ShaderLibraryFile\n"
        "{\n"
        "    const char* name;\n"
        "    const char* text;\n"
        "};\n"
        "\n"
        "const ShaderLibraryFile kFiles[] = {\n")

    foreach(ENGINE_SHADER_LIB_FILE ${ENGINE_SHADER_LIB_FILES})
        set(ENGINE_SHADER_LIB_PATH "${ENGINE_SHADER_LIB_ROOT}/${ENGINE_SHADER_LIB_FILE}")

        if(NOT EXISTS "${ENGINE_SHADER_LIB_PATH}")
            message(FATAL_ERROR "engine_embed_shader_library: no such file: ${ENGINE_SHADER_LIB_PATH}")
        endif()

        # So that editing a .jsl re-runs CMake and regenerates this. Without
        # it the text would be whatever it was at the last configure, and a
        # shader edit would appear to do nothing.
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ENGINE_SHADER_LIB_PATH}")

        file(READ "${ENGINE_SHADER_LIB_PATH}" ENGINE_SHADER_LIB_TEXT)

        # The text goes in as a raw string literal, so it needs a delimiter
        # that does not appear inside it. Checked rather than assumed: a
        # file that happened to contain the terminator would otherwise
        # generate a source that fails to compile somewhere far from here.
        string(FIND "${ENGINE_SHADER_LIB_TEXT}" ")FLUXIONJSL\"" ENGINE_SHADER_LIB_CLASH)
        if(NOT ENGINE_SHADER_LIB_CLASH EQUAL -1)
            message(FATAL_ERROR
                "engine_embed_shader_library: ${ENGINE_SHADER_LIB_FILE} contains the raw-string terminator "
                "')FLUXIONJSL\"', which would end the generated literal early")
        endif()

        string(APPEND ENGINE_SHADER_LIB_BODY
            "    { \"${ENGINE_SHADER_LIB_FILE}\", R\"FLUXIONJSL(${ENGINE_SHADER_LIB_TEXT})FLUXIONJSL\" },\n")
    endforeach()

    list(LENGTH ENGINE_SHADER_LIB_FILES ENGINE_SHADER_LIB_COUNT)

    string(APPEND ENGINE_SHADER_LIB_BODY
        "};\n"
        "} // namespace\n"
        "\n"
        "const char* FindShaderLibraryFile(const char* name)\n"
        "{\n"
        "    if (name == nullptr) return nullptr;\n"
        "\n"
        "    for (const ShaderLibraryFile& file : kFiles)\n"
        "    {\n"
        "        const char* a = file.name;\n"
        "        const char* b = name;\n"
        "        while (*a != '\\0' && *a == *b) { ++a; ++b; }\n"
        "        if (*a == '\\0' && *b == '\\0') return file.text;\n"
        "    }\n"
        "    return nullptr;\n"
        "}\n"
        "\n"
        "unsigned int GetShaderLibraryFileCount()\n"
        "{\n"
        "    return ${ENGINE_SHADER_LIB_COUNT}u;\n"
        "}\n"
        "\n"
        "const char* GetShaderLibraryFileNameAt(unsigned int index)\n"
        "{\n"
        "    if (index >= ${ENGINE_SHADER_LIB_COUNT}u) return nullptr;\n"
        "    return kFiles[index].name;\n"
        "}\n"
        "\n"
        "} // namespace Fluxion::RenderCore\n")

    file(WRITE "${ENGINE_SHADER_LIB_GENERATED}" "${ENGINE_SHADER_LIB_BODY}")

    set(${ENGINE_SHADER_LIB_OUTPUT} "${ENGINE_SHADER_LIB_GENERATED}" PARENT_SCOPE)
endfunction()
